esd:
  port:
    http:
      host: 0.0.0.0
      port: 8081
      sock_type: 1
      open_http_protocol: true
    ws:
      host: 0.0.0.0
      port: 8082
      sock_type: 1
      open_websocket_protocol: true
scan:
  include_paths:
    examples: /mnt/c/Users/administrato/PhpstormProjects/easyroute/exampleClass
actor:
  actor_worker_count: 4